// <auto-generated />
using System;
using EFCore.Snowflake.Metadata;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace libcal_etl.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20260421201202_SnowflakeInitial")]
    partial class SnowflakeInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Snowflake:IndexBehavior", SnowflakeIndexBehavior.Disallow);

            SnowflakeModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibCalTypes.AppointmentBooking", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("NUMBER(19,0)")
                        .HasColumnName("ID");

                    b.Property<bool>("Cancelled")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("CANCELLED");

                    b.Property<long>("CategoryId")
                        .HasColumnType("NUMBER(19,0)")
                        .HasColumnName("CATEGORY_ID");

                    b.Property<string>("Directions")
                        .HasColumnType("VARCHAR(16777216)")
                        .HasColumnName("DIRECTIONS");

                    b.Property<DateTimeOffset>("FromDate")
                        .HasColumnType("TIMESTAMP_TZ(9)")
                        .HasColumnName("FROM_DATE");

                    b.Property<string>("Group")
                        .HasColumnType("VARCHAR(16777216)")
                        .HasColumnName("GROUP");

                    b.Property<long>("GroupId")
                        .HasColumnType("NUMBER(19,0)")
                        .HasColumnName("GROUP_ID");

                    b.Property<string>("Location")
                        .HasColumnType("VARCHAR(16777216)")
                        .HasColumnName("LOCATION");

                    b.Property<long>("LocationId")
                        .HasColumnType("NUMBER(19,0)")
                        .HasColumnName("LOCATION_ID");

                    b.Property<DateTimeOffset>("ToDate")
                        .HasColumnType("TIMESTAMP_TZ(9)")
                        .HasColumnName("TO_DATE");

                    b.Property<string>("UserHash")
                        .HasColumnType("VARCHAR(16777216)")
                        .HasColumnName("USER_HASH");

                    b.Property<long>("UserId")
                        .HasColumnType("NUMBER(19,0)")
                        .HasColumnName("USER_ID");

                    b.HasKey("Id")
                        .HasName("PK_LIBCAL_APPOINTMENT_BOOKINGS");

                    b.ToTable("LIBCAL_APPOINTMENT_BOOKINGS", (string)null);

                    b.ToTable(tb => tb.IsPermanent());
                });

            modelBuilder.Entity("LibCalTypes.AppointmentQuestion", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("NUMBER(19,0)")
                        .HasColumnName("ID");

                    b.Property<string>("Label")
                        .HasColumnType("VARCHAR(16777216)")
                        .HasColumnName("LABEL");

                    b.Property<bool>("Required")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("REQUIRED");

                    b.Property<string>("Type")
                        .HasColumnType("VARCHAR(16777216)")
                        .HasColumnName("TYPE");

                    b.HasKey("Id")
                        .HasName("PK_LIBCAL_APPOINTMENT_QUESTIONS");

                    b.ToTable("LIBCAL_APPOINTMENT_QUESTIONS", (string)null);

                    b.ToTable(tb => tb.IsPermanent());
                });

            modelBuilder.Entity("LibCalTypes.AppointmentUser", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("NUMBER(19,0)")
                        .HasColumnName("USER_ID");

                    b.Property<string>("Description")
                        .HasColumnType("VARCHAR(16777216)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("Email")
                        .HasColumnType("VARCHAR(16777216)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("FirstName")
                        .HasColumnType("VARCHAR(16777216)")
                        .HasColumnName("FIRST_NAME");

                    b.Property<string>("LastName")
                        .HasColumnType("VARCHAR(16777216)")
                        .HasColumnName("LAST_NAME");

                    b.Property<string>("Nickname")
                        .HasColumnType("VARCHAR(16777216)")
                        .HasColumnName("NICKNAME");

                    b.Property<string>("Url")
                        .HasColumnType("VARCHAR(16777216)")
                        .HasColumnName("URL");

                    b.HasKey("UserId")
                        .HasName("PK_LIBCAL_APPOINTMENT_USERS");

                    b.ToTable("LIBCAL_APPOINTMENT_USERS", (string)null);

                    b.ToTable(tb => tb.IsPermanent());
                });

            modelBuilder.Entity("LibCalTypes.ArchivedSpaceBooking", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19,0)")
                        .HasColumnName("ID");

                    SnowflakePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BookingFormAnswers")
                        .HasColumnType("VARCHAR(16777216)")
                        .HasColumnName("BOOKING_FORM_ANSWERS");

                    b.Property<string>("BookingId")
                        .HasColumnType("VARCHAR(16777216)")
                        .HasColumnName("BOOKING_ID");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("TIMESTAMP_NTZ(9)")
                        .HasColumnName("CANCELLED_AT");

                    b.Property<string>("CancelledByUser")
                        .HasColumnType("VARCHAR(16777216)")
                        .HasColumnName("CANCELLED_BY_USER");

                    b.Property<string>("Category")
                        .HasColumnType("VARCHAR(16777216)")
                        .HasColumnName("CATEGORY");

                    b.Property<DateTime?>("CheckedInDate")
                        .HasColumnType("TIMESTAMP_NTZ(9)")
                        .HasColumnName("CHECKED_IN_DATE");

                    b.Property<DateTime?>("CheckedOutDate")
                        .HasColumnType("TIMESTAMP_NTZ(9)")
                        .HasColumnName("CHECKED_OUT_DATE");

                    b.Property<string>("Cost")
                        .HasColumnType("VARCHAR(16777216)")
                        .HasColumnName("COST");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TIMESTAMP_NTZ(9)")
                        .HasColumnName("CREATED_DATE");

                    b.Property<DateTime?>("EventEnd")
                        .HasColumnType("TIMESTAMP_NTZ(9)")
                        .HasColumnName("EVENT_END");

                    b.Property<string>("EventId")
                        .HasColumnType("VARCHAR(16777216)")
                        .HasColumnName("EVENT_ID");

                    b.Property<DateTime?>("EventStart")
                        .HasColumnType("TIMESTAMP_NTZ(9)")
                        .HasColumnName("EVENT_START");

                    b.Property<string>("EventTitle")
                        .HasColumnType("VARCHAR(16777216)")
                        .HasColumnName("EVENT_TITLE");

                    b.Property<DateTime?>("FromDate")
                        .HasColumnType("TIMESTAMP_NTZ(9)")
                        .HasColumnName("FROM_DATE");

                    b.Property<string>("Location")
                        .HasColumnType("VARCHAR(16777216)")
                        .HasColumnName("LOCATION");

                    b.Property<string>("ShowedUp")
                        .HasColumnType("VARCHAR(16777216)")
                        .HasColumnName("SHOWED_UP");

                    b.Property<string>("SpaceId")
                        .HasColumnType("NUMBER(19,0)")
                        .HasColumnName("SPACE_ID");

                    b.Property<string>("SpaceName")
                        .HasColumnType("VARCHAR(16777216)")
                        .HasColumnName("SPACE_NAME");

                    b.Property<string>("Status")
                        .HasColumnType("VARCHAR(16777216)")
                        .HasColumnName("STATUS");

                    b.Property<DateTime?>("ToDate")
                        .HasColumnType("TIMESTAMP_NTZ(9)")
                        .HasColumnName("TO_DATE");

                    b.Property<string>("UserHash")
                        .HasColumnType("VARCHAR(16777216)")
                        .HasColumnName("USER_HASH");

                    b.Property<string>("Zone")
                        .HasColumnType("VARCHAR(16777216)")
                        .HasColumnName("ZONE");

                    b.HasKey("Id")
                        .HasName("PK_LIBCAL_ARCHIVED_SPACE_BOOKINGS");

                    b.ToTable("LIBCAL_ARCHIVED_SPACE_BOOKINGS", (string)null);

                    b.ToTable(tb => tb.IsPermanent());
                });

            modelBuilder.Entity("LibCalTypes.Event", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("NUMBER(19,0)")
                        .HasColumnName("ID");

                    b.Property<bool>("AllDay")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("ALL_DAY");

                    b.Property<string>("Color")
                        .HasColumnType("VARCHAR(16777216)")
                        .HasColumnName("COLOR");

                    b.Property<string>("Description")
                        .HasColumnType("VARCHAR(16777216)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<DateTimeOffset>("End")
                        .HasColumnType("TIMESTAMP_TZ(9)")
                        .HasColumnName("END");

                    b.Property<string>("FeaturedImage")
                        .HasColumnType("VARCHAR(16777216)")
                        .HasColumnName("FEATURED_IMAGE");

                    b.Property<bool>("HasRegistrationClosed")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("HAS_REGISTRATION_CLOSED");

                    b.Property<bool>("HasRegistrationOpened")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("HAS_REGISTRATION_OPENED");

                    b.Property<string>("MoreInfo")
                        .HasColumnType("VARCHAR(16777216)")
                        .HasColumnName("MORE_INFO");

                    b.Property<string>("OnlineHostUrl")
                        .HasColumnType("VARCHAR(16777216)")
                        .HasColumnName("ONLINE_HOST_URL");

                    b.Property<string>("OnlineJoinPassword")
                        .HasColumnType("VARCHAR(16777216)")
                        .HasColumnName("ONLINE_JOIN_PASSWORD");

                    b.Property<string>("OnlineJoinUrl")
                        .HasColumnType("VARCHAR(16777216)")
                        .HasColumnName("ONLINE_JOIN_URL");

                    b.Property<string>("OnlineMeetingId")
                        .HasColumnType("VARCHAR(16777216)")
                        .HasColumnName("ONLINE_MEETING_ID");

                    b.Property<string>("OnlineProvider")
                        .HasColumnType("VARCHAR(16777216)")
                        .HasColumnName("ONLINE_PROVIDER");

                    b.Property<long>("OnlineSeats")
                        .HasColumnType("NUMBER(19,0)")
                        .HasColumnName("ONLINE_SEATS");

                    b.Property<long>("OnlineSeatsTaken")
                        .HasColumnType("NUMBER(19,0)")
                        .HasColumnName("ONLINE_SEATS_TAKEN");

                    b.Property<long>("OnlineUserId")
                        .HasColumnType("NUMBER(19,0)")
                        .HasColumnName("ONLINE_USER_ID");

                    b.Property<long>("PhysicalSeats")
                        .HasColumnType("NUMBER(19,0)")
                        .HasColumnName("PHYSICAL_SEATS");

                    b.Property<long>("PhysicalSeatsTaken")
                        .HasColumnType("NUMBER(19,0)")
                        .HasColumnName("PHYSICAL_SEATS_TAKEN");

                    b.Property<string>("Presenter")
                        .HasColumnType("VARCHAR(16777216)")
                        .HasColumnName("PRESENTER");

                    b.Property<bool>("Registration")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("REGISTRATION");

                    b.Property<long?>("Seats")
                        .HasColumnType("NUMBER(19,0)")
                        .HasColumnName("SEATS");

                    b.Property<long>("SeatsTaken")
                        .HasColumnType("NUMBER(19,0)")
                        .HasColumnName("SEATS_TAKEN");

                    b.Property<long>("SetupTime")
                        .HasColumnType("NUMBER(19,0)")
                        .HasColumnName("SETUP_TIME");

                    b.Property<DateTimeOffset>("Start")
                        .HasColumnType("TIMESTAMP_TZ(9)")
                        .HasColumnName("START");

                    b.Property<long>("TeardownTime")
                        .HasColumnType("NUMBER(19,0)")
                        .HasColumnName("TEARDOWN_TIME");

                    b.Property<string>("Title")
                        .HasColumnType("VARCHAR(16777216)")
                        .HasColumnName("TITLE");

                    b.Property<bool>("WaitList")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("WAIT_LIST");

                    b.Property<string>("ZoomEmail")
                        .HasColumnType("VARCHAR(16777216)")
                        .HasColumnName("ZOOM_EMAIL");

                    b.HasKey("Id")
                        .HasName("PK_LIBCAL_EVENTS");

                    b.ToTable("LIBCAL_EVENTS", (string)null);

                    b.ToTable(tb => tb.IsPermanent());
                });

            modelBuilder.Entity("LibCalTypes.SpaceBooking", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("NUMBER(19,0)")
                        .HasColumnName("ID");

                    b.Property<string>("BookId")
                        .HasColumnType("VARCHAR(16777216)")
                        .HasColumnName("BOOK_ID");

                    b.Property<DateTimeOffset?>("Cancelled")
                        .HasColumnType("TIMESTAMP_TZ(9)")
                        .HasColumnName("CANCELLED");

                    b.Property<long>("CategoryId")
                        .HasColumnType("NUMBER(19,0)")
                        .HasColumnName("CATEGORY_ID");

                    b.Property<string>("CategoryName")
                        .HasColumnType("VARCHAR(16777216)")
                        .HasColumnName("CATEGORY_NAME");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("TIMESTAMP_TZ(9)")
                        .HasColumnName("CREATED");

                    b.Property<DateTimeOffset>("FromDate")
                        .HasColumnType("TIMESTAMP_TZ(9)")
                        .HasColumnName("FROM_DATE");

                    b.Property<long>("ItemId")
                        .HasColumnType("NUMBER(19,0)")
                        .HasColumnName("ITEM_ID");

                    b.Property<string>("ItemName")
                        .HasColumnType("VARCHAR(16777216)")
                        .HasColumnName("ITEM_NAME");

                    b.Property<long>("LocationId")
                        .HasColumnType("NUMBER(19,0)")
                        .HasColumnName("LOCATION_ID");

                    b.Property<string>("LocationName")
                        .HasColumnType("VARCHAR(16777216)")
                        .HasColumnName("LOCATION_NAME");

                    b.Property<string>("Status")
                        .HasColumnType("VARCHAR(16777216)")
                        .HasColumnName("STATUS");

                    b.Property<DateTimeOffset>("ToDate")
                        .HasColumnType("TIMESTAMP_TZ(9)")
                        .HasColumnName("TO_DATE");

                    b.Property<string>("UserHash")
                        .HasColumnType("VARCHAR(16777216)")
                        .HasColumnName("USER_HASH");

                    b.HasKey("Id")
                        .HasName("PK_LIBCAL_SPACE_BOOKINGS");

                    b.ToTable("LIBCAL_SPACE_BOOKINGS", (string)null);

                    b.ToTable(tb => tb.IsPermanent());
                });

            modelBuilder.Entity("LibCalTypes.AppointmentBooking", b =>
                {
                    b.OwnsMany("LibCalTypes.QuestionAnswer", "Answers", b1 =>
                        {
                            b1.Property<long>("BookingId")
                                .HasColumnType("NUMBER(19,0)")
                                .HasColumnName("BOOKING_ID");

                            b1.Property<long>("QuestionId")
                                .HasColumnType("NUMBER(19,0)")
                                .HasColumnName("QUESTION_ID");

                            b1.Property<string>("Answer")
                                .HasColumnType("VARCHAR(16777216)")
                                .HasColumnName("ANSWER");

                            b1.HasKey("BookingId", "QuestionId")
                                .HasName("PK_LIBCAL_QUESTION_ANSWERS");

                            b1.ToTable("LIBCAL_QUESTION_ANSWERS", (string)null);

                            b1.ToTable(tb => tb.IsPermanent());

                            b1.WithOwner()
                                .HasForeignKey("BookingId")
                                .HasConstraintName("FK_LIBCAL_QUESTION_ANSWERS_LIBCAL_APPOINTMENT_BOOKINGS_BOOKING_ID");

                            b1.HasOne("LibCalTypes.AppointmentQuestion", null)
                                .WithMany()
                                .HasForeignKey("QuestionId")
                                .OnDelete(DeleteBehavior.NoAction)
                                .IsRequired()
                                .HasConstraintName("FK_LIBCAL_QUESTION_ANSWERS_APPOINTMENT_QUESTION_QUESTION_ID");
                        });

                    b.Navigation("Answers");
                });

            modelBuilder.Entity("LibCalTypes.AppointmentQuestion", b =>
                {
                    b.OwnsMany("LibCalTypes.QuestionOption", "Options", b1 =>
                        {
                            b1.Property<long>("QuestionId")
                                .HasColumnType("NUMBER(19,0)")
                                .HasColumnName("QUESTION_ID");

                            b1.Property<string>("Option")
                                .HasColumnType("VARCHAR(16777216)")
                                .HasColumnName("OPTION");

                            b1.HasKey("QuestionId", "Option")
                                .HasName("PK_LIBCAL_QUESTION_OPTIONS");

                            b1.ToTable("LIBCAL_QUESTION_OPTIONS", (string)null);

                            b1.ToTable(tb => tb.IsPermanent());

                            b1.WithOwner()
                                .HasForeignKey("QuestionId")
                                .HasConstraintName("FK_LIBCAL_QUESTION_OPTIONS_LIBCAL_APPOINTMENT_QUESTIONS_QUESTION_ID");
                        });

                    b.Navigation("Options");
                });

            modelBuilder.Entity("LibCalTypes.Event", b =>
                {
                    b.OwnsOne("LibCalTypes.Calendar", "Calendar", b1 =>
                        {
                            b1.Property<long>("EventId")
                                .HasColumnType("NUMBER(19,0)")
                                .HasColumnName("ID");

                            b1.Property<string>("Admin")
                                .HasColumnType("VARCHAR(16777216)")
                                .HasColumnName("CALENDAR_ADMIN");

                            b1.Property<long>("Id")
                                .HasColumnType("NUMBER(19,0)")
                                .HasColumnName("CALENDAR_ID");

                            b1.Property<string>("Name")
                                .HasColumnType("VARCHAR(16777216)")
                                .HasColumnName("CALENDAR_NAME");

                            b1.Property<string>("Public")
                                .HasColumnType("VARCHAR(16777216)")
                                .HasColumnName("CALENDAR_PUBLIC");

                            b1.HasKey("EventId");

                            b1.ToTable("LIBCAL_EVENTS");

                            b1.ToTable(tb => tb.IsPermanent());

                            b1.WithOwner()
                                .HasForeignKey("EventId")
                                .HasConstraintName("FK_LIBCAL_EVENTS_LIBCAL_EVENTS_ID");
                        });

                    b.OwnsOne("LibCalTypes.Campus", "Campus", b1 =>
                        {
                            b1.Property<long>("EventId")
                                .HasColumnType("NUMBER(19,0)")
                                .HasColumnName("ID");

                            b1.Property<long>("Id")
                                .HasColumnType("NUMBER(19,0)")
                                .HasColumnName("CAMPUS_ID");

                            b1.Property<string>("Name")
                                .HasColumnType("VARCHAR(16777216)")
                                .HasColumnName("CAMPUS_NAME");

                            b1.HasKey("EventId");

                            b1.ToTable("LIBCAL_EVENTS");

                            b1.ToTable(tb => tb.IsPermanent());

                            b1.WithOwner()
                                .HasForeignKey("EventId")
                                .HasConstraintName("FK_LIBCAL_EVENTS_LIBCAL_EVENTS_ID");
                        });

                    b.OwnsMany("LibCalTypes.Category", "Category", b1 =>
                        {
                            b1.Property<long>("EventId")
                                .HasColumnType("NUMBER(19,0)")
                                .HasColumnName("EVENT_ID");

                            b1.Property<long>("Id")
                                .HasColumnType("NUMBER(19,0)")
                                .HasColumnName("ID");

                            b1.Property<string>("Name")
                                .HasColumnType("VARCHAR(16777216)")
                                .HasColumnName("NAME");

                            b1.HasKey("EventId", "Id")
                                .HasName("PK_LIBCAL_CATEGORIES");

                            b1.ToTable("LIBCAL_CATEGORIES", (string)null);

                            b1.ToTable(tb => tb.IsPermanent());

                            b1.WithOwner()
                                .HasForeignKey("EventId")
                                .HasConstraintName("FK_LIBCAL_CATEGORIES_LIBCAL_EVENTS_EVENT_ID");
                        });

                    b.OwnsOne("LibCalTypes.Location", "Location", b1 =>
                        {
                            b1.Property<long>("EventId")
                                .HasColumnType("NUMBER(19,0)")
                                .HasColumnName("ID");

                            b1.Property<long>("Id")
                                .HasColumnType("NUMBER(19,0)")
                                .HasColumnName("LOCATION_ID");

                            b1.Property<string>("Name")
                                .HasColumnType("VARCHAR(16777216)")
                                .HasColumnName("LOCATION_NAME");

                            b1.Property<long>("Type")
                                .HasColumnType("NUMBER(19,0)")
                                .HasColumnName("LOCATION_TYPE");

                            b1.HasKey("EventId");

                            b1.ToTable("LIBCAL_EVENTS");

                            b1.ToTable(tb => tb.IsPermanent());

                            b1.WithOwner()
                                .HasForeignKey("EventId")
                                .HasConstraintName("FK_LIBCAL_EVENTS_LIBCAL_EVENTS_ID");
                        });

                    b.OwnsOne("LibCalTypes.Owner", "Owner", b1 =>
                        {
                            b1.Property<long>("EventId")
                                .HasColumnType("NUMBER(19,0)")
                                .HasColumnName("ID");

                            b1.Property<long>("Id")
                                .HasColumnType("NUMBER(19,0)")
                                .HasColumnName("OWNER_ID");

                            b1.Property<string>("Name")
                                .HasColumnType("VARCHAR(16777216)")
                                .HasColumnName("OWNER_NAME");

                            b1.HasKey("EventId");

                            b1.ToTable("LIBCAL_EVENTS");

                            b1.ToTable(tb => tb.IsPermanent());

                            b1.WithOwner()
                                .HasForeignKey("EventId")
                                .HasConstraintName("FK_LIBCAL_EVENTS_LIBCAL_EVENTS_ID");
                        });

                    b.OwnsMany("LibCalTypes.Registrant", "Registrants", b1 =>
                        {
                            b1.Property<long>("BookingId")
                                .HasColumnType("NUMBER(19,0)")
                                .HasColumnName("BOOKING_ID");

                            b1.Property<string>("Attendance")
                                .HasColumnType("VARCHAR(16777216)")
                                .HasColumnName("ATTENDANCE");

                            b1.Property<string>("Barcode")
                                .HasColumnType("VARCHAR(16777216)")
                                .HasColumnName("BARCODE");

                            b1.Property<long>("EventId")
                                .HasColumnType("NUMBER(19,0)")
                                .HasColumnName("EVENT_ID");

                            b1.Property<DateTimeOffset>("RegisteredDate")
                                .HasColumnType("TIMESTAMP_TZ(9)")
                                .HasColumnName("REGISTERED_DATE");

                            b1.Property<string>("RegistrationType")
                                .HasColumnType("VARCHAR(16777216)")
                                .HasColumnName("REGISTRATION_TYPE");

                            b1.Property<string>("UserHash")
                                .HasColumnType("VARCHAR(16777216)")
                                .HasColumnName("USER_HASH");

                            b1.HasKey("BookingId")
                                .HasName("PK_LIBCAL_EVENT_REGISTRANTS");

                            b1.ToTable("LIBCAL_EVENT_REGISTRANTS", (string)null);

                            b1.ToTable(tb => tb.IsPermanent());

                            b1.WithOwner()
                                .HasForeignKey("EventId")
                                .HasConstraintName("FK_LIBCAL_EVENT_REGISTRANTS_LIBCAL_EVENTS_EVENT_ID");
                        });

                    b.OwnsOne("LibCalTypes.Url", "Url", b1 =>
                        {
                            b1.Property<long>("EventId")
                                .HasColumnType("NUMBER(19,0)")
                                .HasColumnName("ID");

                            b1.Property<string>("Admin")
                                .HasColumnType("VARCHAR(16777216)")
                                .HasColumnName("URL_ADMIN");

                            b1.Property<string>("Public")
                                .HasColumnType("VARCHAR(16777216)")
                                .HasColumnName("URL_PUBLIC");

                            b1.HasKey("EventId");

                            b1.ToTable("LIBCAL_EVENTS");

                            b1.ToTable(tb => tb.IsPermanent());

                            b1.WithOwner()
                                .HasForeignKey("EventId")
                                .HasConstraintName("FK_LIBCAL_EVENTS_LIBCAL_EVENTS_ID");
                        });

                    b.OwnsMany("LibCalTypes.FutureDate", "FutureDates", b1 =>
                        {
                            b1.Property<long>("OriginalEventId")
                                .HasColumnType("NUMBER(19,0)")
                                .HasColumnName("ORIGINAL_EVENT_ID");

                            b1.Property<long>("FutureEventId")
                                .HasColumnType("NUMBER(19,0)")
                                .HasColumnName("FUTURE_EVENT_ID");

                            b1.Property<DateTimeOffset>("Start")
                                .HasColumnType("TIMESTAMP_TZ(9)")
                                .HasColumnName("START");

                            b1.HasKey("OriginalEventId", "FutureEventId")
                                .HasName("PK_LIBCAL_FUTURE_DATES");

                            b1.ToTable("LIBCAL_FUTURE_DATES", (string)null);

                            b1.ToTable(tb => tb.IsPermanent());

                            b1.WithOwner()
                                .HasForeignKey("OriginalEventId")
                                .HasConstraintName("FK_LIBCAL_FUTURE_DATES_LIBCAL_EVENTS_ORIGINAL_EVENT_ID");
                        });

                    b.Navigation("Calendar");

                    b.Navigation("Campus");

                    b.Navigation("Category");

                    b.Navigation("FutureDates");

                    b.Navigation("Location");

                    b.Navigation("Owner");

                    b.Navigation("Registrants");

                    b.Navigation("Url");
                });
#pragma warning restore 612, 618
        }
    }
}
